import{useState}from 'react'
import s from './JoinAsDoctor.module.css'
export default function JoinAsDoctor(){
const[f,setF]=useState({name:'',email:'',specialty:'',country:'',experience:'',message:''})
const[sent,setSent]=useState(false)
const h=e=>setF({...f,[e.target.name]:e.target.value})
const sub=e=>{e.preventDefault();setSent(true)}
return(<section id="join-doctors" className={s.s}><div className={s.i}><div className={s.left}><span className={s.l}>For Doctors</span><h2>Join Orsenta as a <em>freelance doctor</em></h2><p>Set your own schedule, consult patients online, and get paid per consultation. We verify your credentials and connect you with patients.</p><div className={s.perks}><div className={s.perk}><span>💰</span><div><strong>Earn per consultation</strong><p>Set your own rate. Get paid after each session.</p></div></div><div className={s.perk}><span>🕐</span><div><strong>Flexible schedule</strong><p>Work when you want. Accept or decline freely.</p></div></div><div className={s.perk}><span>✅</span><div><strong>Verified and trusted</strong><p>We review your credentials so patients trust you.</p></div></div><div className={s.perk}><span>🌍</span><div><strong>Global reach</strong><p>Consult patients from anywhere in the world.</p></div></div></div></div><div className={s.right}>{sent?(<div className={s.ok}><div className={s.ck}>✓</div><h3>Application received!</h3><p>Our team will review your credentials and contact you within 3 to 5 business days.</p></div>):(<form className={s.form} onSubmit={sub}><h3>Apply to join our network</h3><p className={s.fs}>Fill in your details and we will review your application.</p><div className={s.row}><div className={s.fi}><label>Full name</label><input name="name" value={f.name} onChange={h} placeholder="Dr. John Smith" required/></div><div className={s.fi}><label>Email</label><input type="email" name="email" value={f.email} onChange={h} placeholder="doctor@email.com" required/></div></div><div className={s.row}><div className={s.fi}><label>Specialty</label><select name="specialty" value={f.specialty} onChange={h} required><option value="">Select specialty</option><option>General Practice</option><option>Cardiology</option><option>Dermatology</option><option>Mental Health</option><option>Pediatrics</option><option>Gynecology</option><option>Neurology</option><option>Orthopedics</option><option>Other</option></select></div><div className={s.fi}><label>Country</label><input name="country" value={f.country} onChange={h} placeholder="Your country" required/></div></div><div className={s.fi}><label>Years of experience</label><input name="experience" value={f.experience} onChange={h} placeholder="e.g. 5 years" required/></div><div className={s.fi}><label>Tell us about yourself</label><textarea name="message" value={f.message} onChange={h} placeholder="Brief background and why you want to join..." rows={4}/></div><p className={s.note}>You will be asked to upload your medical license after submission.</p><button type="submit" className={s.sub}>Submit application</button></form>)}</div></div></section>)
}
